remove profiles

diff --git a/templates/codium/haskell/.github/workflows/ci.yaml b/templates/codium/haskell/.github/workflows/ci.yaml
--- a/templates/codium/haskell/.github/workflows/ci.yaml
+++ b/templates/codium/haskell/.github/workflows/ci.yaml
@@ -6,30 +6,54 @@ jobs:
       - name: Checkout this repo
         uses: actions/checkout@v3
       - name: Install Nix
-        uses: cachix/install-nix-action@v18
+        uses: nixbuild/nix-quick-install-action@v25
         with:
-          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}\nsubstituters = https://cache.nixos.org/ https://cache.iog.io https://nix-community.cachix.org https://deemp.cachix.org \ntrusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= haskell-language-server.cachix.org-1:juFfHrwkOxqIOZShtC4YC1uT1bBcq2RSvC7OMKx0Nz8= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=\n"
-          install_url: https://releases.nixos.org/nix/nix-2.11.1/install
-      - if: matrix.os == 'ubuntu-20.04'
+          nix_conf: |
+            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
+            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io https://deemp.cachix.org
+            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
+            keep-outputs = true
+      - name: Restore and cache Nix store
+        uses: deemp/cache-nix-too@v1
+        with:
+          key: nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
+          linux-gc-enabled: true
+          linux-max-store-size: 0
+          macos-gc-enabled: true
+          macos-max-store-size: 0
+          restore-keys: |
+            nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
+            nix-${{ matrix.os }}-cachix-
+      - if: matrix.os == 'ubuntu-22.04'
         name: Config git for github-actions
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
-      - if: matrix.os == 'ubuntu-20.04'
+      - if: matrix.os == 'ubuntu-22.04'
+        name: Format Nix files
+        run: |+
+          nix run .#format
+          nix profile install .#format
+
+      - if: matrix.os == 'ubuntu-22.04'
         name: Update flake locks
-        run: |
+        run: |+
           git pull --rebase --autostash
+
           nix run .#updateLocks
-          git commit -a -m "action: Update flake locks" && git push || echo ""
-      - name: Log in to Cachix
-        uses: cachix/cachix-action@v12
-        with:
-          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
-          name: ${{ secrets.CACHIX_CACHE }}
+          nix profile install .#updateLocks
+
+          git commit -a -m "action: Update flake locks" \
+                                 && git push || echo "push failed!"
+
       - env:
+          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
           CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
         name: Push flakes to Cachix
-        run: nix run .#pushToCachix
+        run: |+
+          nix run .#pushToCachix
+          nix profile install .#pushToCachix
+
     strategy:
       matrix:
         os:
