upd workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,30 +19,30 @@ jobs:
       - name: Restore and cache Nix store
         uses: nix-community/cache-nix-action@v1
         with:
-          key: nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
+          key: nix-${{ matrix.os }}-job-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
           linux-gc-enabled: true
           linux-max-store-size: 5000000000
           macos-gc-enabled: true
           macos-max-store-size: 5000000000
           restore-keys: |
-            nix-${{ matrix.os }}-cachix-
+            nix-${{ matrix.os }}-job-
       - name: Remove old cache profiles
         run: rm -rf /nix/var/nix/profiles/cache
       - if: matrix.os == 'ubuntu-22.04'
-        name: Config git for github-actions
+        name: Configure git for github-actions
         run: |
           git config --global user.name github-actions
           git config --global user.email github-actions@github.com
-      - if: matrix.os == 'ubuntu-22.04'
-        name: Format Nix files
-        run: |-
-          nix profile install .#format
-          nix run .#format
       - if: matrix.os == 'ubuntu-22.04'
         name: Update flake locks
         run: |-
           nix profile install .#updateLocks
           nix run .#updateLocks
+      - if: matrix.os == 'ubuntu-22.04'
+        name: Format Nix files
+        run: |-
+          nix profile install .#format
+          nix run .#format
       - if: matrix.os == 'ubuntu-22.04'
         name: Write workflows
         run: |-
@@ -64,38 +64,36 @@ jobs:
           nix run .#writeWorkflows
           cd $ROOT_DIR
       - if: matrix.os == 'ubuntu-22.04'
-        name: Commit and push
-        run: |
+        name: Update docs
+        run: |-
+          nix profile install .#genDocs
+          nix run .#genDocs
+      - if: matrix.os == 'ubuntu-22.04'
+        name: Commit & Push
+        run: |-
           git pull --rebase --autostash
 
           git add .
+
           git commit \
-            -m "action: Update flake locks" \
-            -m "action: Format Nix files" \
-            -m "action: Write workflows"
+            -m "action" \
+            -m "Update flake locks" \
+            -m "Format Nix files" \
+            -m "Write workflows" \
+            -m "Update docs" \
+            || echo "commit failed!"
+
           git push
       - if: matrix.os == 'ubuntu-22.04'
-        name: Build docs
-        run: |
-          nix profile install .#genDocs
-          nix run .#genDocs
-          cp -r docs/book docs/dist
+        name: Copy docs
+        run: cp -r docs/book docs/dist
       - if: matrix.os == 'ubuntu-22.04'
-        name: Update docs
-        run: |
-          git add "docs/src"
-          git commit -a -m "Update docs" && git push || echo "push failed!"
-      - if: matrix.os == 'ubuntu-22.04'
-        name: GitHub Pages action
+        name: Publish docs on GitHub Pages
         uses: peaceiris/actions-gh-pages@v3.9.3
         with:
           force_orphan: true
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: docs/dist
-      - if: matrix.os == 'ubuntu-22.04'
-        name: Remove dist dir
-        run: |
-          rm -rf "docs/dist"
       - name: Save flakes
         run: |-
           nix profile install .#saveFlakes
